export const COLORS = {
  primary: "#00c194",
  primary_soft: "#7df0d5",
  bg_primary: "#E0FAF4",
  button: {
    active: "#00c194",
    disabled: "#5c9988",
  },
  bg_splash: "#ffffff",
  badges: {
    _top: "#f39f0a",
    featured: "#e5f8f7",
    _bump_up: "#f39f0a",
    "is-sold": "#1aa78e",
    "is-popular": "#14e0ad",
    bg: {
      "is-popular": "#14e0ad",
      "is-featured": "#f85c70",
      "is-top": "#f85c70",
      "is-bump-up": "#f85c70",
      new: "#f85c70",
      "is-popular": "#f85c70",
      popular: "#f85c70",
    },
    text: {
      "is-popular": "#ffffff",
      "is-featured": "#ffffff",
      "is-top": "#ffffff",
      "is-bump-up": "#ffffff",
      new: "#ffffff",
      "is-popular": "#ffffff",
      popular: "#ffffff",
    },
  },

  promotions: {
    bg: {
      featured: "#f39f0a",
      _top: "#f39f0a",
      _bump_up: "#f39f0a",
    },
    text: {
      featured: "#ffffff",
      _top: "#ffffff",
      _bump_up: "#ffffff",
    },
  },
  cardBg: {
    _top: "#ffe3b0",
    featured: "#e5f8f7",
    "is-popular": "#c4fff0",
  },
  bg_light: "#f9f9f9",
  bg_dark: "#f0f0f0",
  text_gray: "#838383",
  text_dark: "#111",
  text_medium: "#4f4f4f",
  white: "#fff",
  black: "#000",
  gray: "gray",
  blue: "#00f",
  red: "#f00",
  dark_green: "#155724",
  green: "#25A01B",
  light_green: "#d4edda",
  yellow: "yellow",
  yellow_dark: "#e0cb2d",
  dodgerblue: "dodgerblue",
  orange: "#ff6600",
  border_light: "#cfcfcf",
  border_dark: "gray",
  separator_light: "#e7e7e7",
  packageCardHeader: "#8a6fdf",
  rating_star: "#ffb400",
  accountSB_bg: "#E0FAF4",
  facebookLogin_bg: "#1877F2",
  googleLogin_bg: "#34A853",
  paymentStatus: {
    success: {
      text: "#00C194",
      bg: "#E0FAF4",
    },
    cancelled: {
      text: "#F65D71",
      bg: "#FFF1F3",
    },
    pending: {
      text: "#FBAC00",
      bg: "#FFF9EC",
    },
  },
};
